In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn import linear_model
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.bedrooms.median()

4.0

In [8]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [19]:
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [20]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
reg=linear_model.LinearRegression()

In [17]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [18]:
reg.coef_ 

array([  112.06244194, 23388.88007794, -3231.71790863])

In [22]:
reg.intercept_

221323.00186540384

In [23]:
#for multiple variable y=m1*x1+m2*x2+m3*x3+b
reg.predict([[2600,3,20]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([518217.63297611])

In [26]:
2600* 112.06244194+3*23388.88007794+20*-3231.71790863+221323.00186540384

518217.63297062385

In [32]:
#predict 3000 area , 3 bedrooms and 40 yrs
reg.predict([[3000,3,40]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [34]:
#predict 2500 area , 4 bedrooms and 5 yrs
reg.predict([[2500,4,5]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])